openapi: 3.0.3
info:
  title: TreeBrowser
  description: TreeBrowser
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: "Development server"
paths:
  /api/tree.php:
    get:
      summary: Get tree
      description: Get tree
      responses:
        '200':
          description: A JSON object containing the tree
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tree'

components:
  schemas:
    Tree:
      type: object
      properties:
        id:
          type: integer
          description: The ID of the tree
        name:
          type: string
          description: The name of the tree